---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:

     # - name: "Include 17_tut_molecule"
     #   ansible.builtin.include_role:
     #     name: "17_tut_molecule"

     - name: Update apt cache ( on Debian )
       apt:
         update_cache: true
         cache_valid_time: 3600
       when: ansible_os_family == "Debian"

- import_playbook: ../../main.yaml

