version: '3.8'

services:
  
  # ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

  db:
    image: postgres
    container_name: ${DATABASE_HOST}
    env_file: .env
    restart: unless-stopped
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - $DATABASE_PORT:$DATABASE_PORT
    networks:
      - app_network
    volumes:
      - db_volume:/var/lib/mysql

  # ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
  
  mario_api:
    container_name: mario_api
    restart: unless-stopped
    env_file: .env
    build: .
    depends_on:
      - db 
    ports:
      - $API_PORT:$API_PORT
    expose:
      - $API_PORT
    networks:
      - app_network

  # ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

  # mario_client:
  #   container_name: mario_client
  #   restart: unless-stopped
  #   build: ../client
  #   ports:
  #     - $CLIENT_PORT:$CLIENT_PORT
  #   expose:
  #     - $CLIENT_PORT
  #   networks:
  #     - app_network


# ------------------------------------ 

networks:
  app_network:

volumes: 
  db_volume:
