- name: Run Ansible tut 2
  hosts: techhive
  become: true
    
  # ------------------------------------------
  
  vars_files:
    - vars.yml

  
  # ------------------------------------------
  
  handlers:
    - name: some thing changed handler 
      debug:
        msg: "changed {{ author }}"


  # ------------------------------------------
 
  pre_tasks:
    - name: Update package cache if needed
      ansible.builtin.package:
        update_cache: yes
        cache_valid_time: 3600
      notify: some thing changed handler         
    
    - name: display variable author 
      debug:
        msg: "hello {{ author }}"


  # ------------------------------------------

  tasks:
    - name: Ping the tech-hive Server
      ansible.builtin.ping: 
  
    
    - name: Get Date iso string  
      debug: 
        var: ansible_date_time['iso8601']
  
  # ------------------------------------------
