- name: Run Ansible Tut 4
  hosts: all
  become: true

  # - - - - - - - - - - - - - - - - - -
  
  vars_files:
  - vars/{{ansible_os_family}}.yml
  
  
  # - - - - - - - - - - - - - - - - - -

  tasks:
    - name: Ping Servers
      ansible.builtin.ping:
        
    - name: Distribution
      debug: msg="{{ ansible_distribution }}"
    
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"
    
    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"
    
    - name: Ansible OS Family 
      debug: msg="{{ ansible_os_family }}"

    - name: Install Ansible for {{ ansible_distribution }} / {{ ansible_os_family }}
      debug: msg=" {{ ansible_distribution }} / {{ ansible_os_family }} "

    - name: Name of Apache Package in {{ ansible_distribution }}
      debug: msg="{{ apache_package }}"

