#   It's better to be safe than to be sorry
- name: Ansible Vault Tutorial
  hosts: all
  become: true
  gather_facts: false

  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: Ping Server 
      ping:

    - name: Command to encrypt a vault in ansible
      debug:
        msg: "ansible-vault encrypt file_path"

    - name: Command to decrypt a vault in ansible
      debug:
        msg: "ansible-vault decrypt file_path"

    - name: Command to edit a vault in ansible
      debug:
        msg: "ansible-vault edit file_path"
    
    - name: Command to rekey a vault password in ansible
      debug:
        msg: "ansible-vault rekey file_path"
    
    - name: Echo The api key  which was injected into the environment
      shell: echo $API_KEY
      environment: 
        API_KEY : "{{ myapp_api_key }}"
      register: echo_result


    - name: show the echo_result
      debug: var=echo_result.stdout

