# Build / Deploy Steps
# ----------------------------------------
# Running Playbooks 
#   1. Install Docker / Docker Composer  
#   2. Install Nginx
#   3. Clone / Pull then Deploy app 
# ---------------------------------------------

- name: Install Build, Deploy Dockerized App 
  hosts: all
  become: true

  # =====================================================

  tasks:
    - name: Install Docker / Docker-Composer
      import_playbook: ./playbooks/1.install_docker.yml

    - name: Install Nginx / Certbot 
      import_playbook: ./playbooks/2.install_nginx.yml

    # - name: Deploy App
    #   import_playbook: ./playbooks/3.deploy_app.yml

    