#   It's better to be safe than to be sorry
- name: Ansible Roles Tutorial
  hosts: all
  become: true

  # - - - - - - - - - - - - - - - - - - - - - -

  vars_files:
    - ../vars/vars.yml

  # - - - - - - - - - - - - - - - - - - - - - -

  tasks:
    - name: Take out of load balancer pool
      ansible.builtin.ping:
      # delegate_to: 127.0.0.1
