- name: "Install and Start Nginx Service on AWS techihve master machine"
  hosts: all
  become: true

  # - - - - - - - - - - - - - - - - - -

  vars:
    project_name: "test"
    my_nginx_conf_path: "/Users/mario/Mario/DevOps/Ansible/tut_10-nginx/ng.conf"
    server_nginx_conf_path: "/etc/nginx/conf.d/{{project_name}}.conf"
    domain: "devops.techhive.dev"

  # - - - - - - - - - - - - - - - - - -

  tasks:
    - name: "Ensure Nginx, Certbot, Pyhton3-Certbot-Nginx is Installed"
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - nginx
        - certbot
        - python3-certbot-nginx


    - name: "Ensure Nginx Service is Started"
      ansible.builtin.service:
        name: nginx
        state: started


    - name: "Copy the nginx config file and restart nginx"
      ansible.builtin.copy:
        src: "{{ my_nginx_conf_path }}"
        dest: "{{ server_nginx_conf_path }}"


    - name: "Ensure Nginx Service is Restarted"
      ansible.builtin.service:
        name: nginx
        state: restarted


    - name: "Setup Certbot for nginx"
      ansible.builtin.shell: > 
        certbot --nginx 
        -d {{ domain }} 
        -m techhivedevs@gmail.com 
        --non-interactive --agree-tos
