---
- name: Testing and Linting Tutorial
  hosts: localhost
  connection: local

  # Ansible Testing Spectrum                 Increase Complexity
  # =========================               ======================
  # 1. ansible-playbook --syntax-check                |
  # 2. ansible-lint                                   |
  # 3. molecule test (intergration)                   |
  # 4. ansible-playbook --check (against prod)        |
  # 5. Parallel Infrastructure                        V

  vars:
    should_fail_via_fail: false
    should_fail_via_assert: false
    should_fail_via_complex_assert: false

  roles:
    - mario

  tasks:
    - name: Print screen
      ansible.builtin.debug:
        msg: "hello world"

    - name: Fail if the conditions warrant a failure
      ansible.builtin.fail:
        msg: "There is failiure here"
      when: should_fail_via_fail

    - name: Stop playbook if an assert isn't validated
      ansible.builtin.assert:
        that: "should_fail_via_assert != true"

    - name: Assertions can multiple conditions
      ansible.builtin.assert:
        that:
          - "should_fail_via_fail != true"
          - "should_fail_via_assert != true"
          - "should_fail_via_complex_assert == false"
