- name: "Install and Start Nginx Service on AWS techihve master"
  hosts: all
  become: true

  # - - - - - - - - - - - - - - - - - - - - - -
  
  vars_files:
  - ../vars/vars.yml

  # - - - - - - - - - - - - - - - - - - - - - -

  tasks:
    - name: Get Number of Cores
      ansible.builtin.debug:
        msg: "cores {{ ansible_processor_vcpus }}"


    - name: "Start {{ nginx_container_name }} container"
      community.docker.docker_container:
        name: "{{ nginx_container_name }}"
        image: "{{ nginx_container_image }}"
        state: started
        ports:
          - "{{ nginx_container_exposed_port }}"


     # - name: Template the nginx config file and restart nginx
       # ansible.builtin.template:
         # src: "{{ playbook_dir }}/../templates/nginx.default.html.j2"
         # dest: "/var/www/html/index.html"
