- name : Run Ansible Tut 6 ( Database backup )
  hosts: all 
  become: true

  # - - - - - - - - - - - - - - - - - -

  vars:

    myhost_path: "/Users/mario/Mario/work/backup/myshop/"
    
    # ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~   

    myshop_test_db_docker: "myshop_database"
    myshop_test_db_name: "my_shop"
    myshop_test_db_username: "root"
    myshop_test_db_password: "secret"
    myshop_test_db_path: "/root/backups/my_shop/my_shop_{{ ansible_date_time['date'] }}.sql"

    # ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~   

    sal_test_db_docker: "sal_db"
    sal_test_db_name: "sal"
    sal_test_db_username: "root"
    sal_test_db_password: "secret"
    sal_test_db_path: "/root/backups/my_shop/my_shop_{{ ansible_date_time['date'] }}.sql"

    # docker exec CONTAINER /usr/bin/mysqldump -u root --password=root DATABASE > backup.sql
    

  # - - - - - - - - - - - - - - - - - -

  tasks:
    - name: "Backup {{ myshop_test_db_docker }} Docker Database "
      ansible.builtin.shell: >
        docker exec {{ myshop_test_db_docker }}
        /usr/bin/mysqldump 
        -u {{ myshop_test_db_username }}
        --password={{ myshop_test_db_password }}
        {{ myshop_test_db_name }}  > 
        {{ myshop_test_db_path }}
    
    - name: Copy {{ myshop_test_db_docker }} sql From Remote Contabo to Local.
      ansible.builtin.fetch:
        src: "{{ myshop_test_db_path }}"
        dest: "{{ myhost_path }}"
        flat: yes


    



